spring.application.name=autodrive
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_alquilerdevehiculos
spring.datasource.username=root
spring.datasource.password=Ale270603

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
